### ISSUE TITLE
Link issue page

### ISSUE THREAD

**Issue by hugohfsouza** [hugohfsouza/GodEye#7]
Link the session text "https://github.com/hugohfsouza/GodEye#support" to the issue page

**Comment by itsabhianant** [comment]
Hi @hugohfsouza,

I would like to work on this issue also.
As per my understanding, I think that you want to link the issue page of this project to your README.md.
If I got your problem right then please do assign this issue to me. If I misunderstood your issue please tell me what is to be done.
It would be nice if you assign me the issue after explaining your issue.

Best,
Abhishek

**Comment by hugohfsouza** [comment]
Hello @itsabhianant 

That's right. I'll assign the issue to you

Thank you very much
